version: 2.0
jobs:
  build:
    working_directory: ~/datadog
    docker:
      - image: fpco/stack-build:latest

    steps:
      - checkout
      - restore_cache:
          keys:
            - dot-stack-{{ checksum "stack.yaml" }}-{{ checksum "datadog.cabal" }}
            - dot-stack
      - restore_cache:
          key: stack-work-{{ checksum "stack.yaml" }}

      - run: stack setup
      - run: stack build --test --no-run-tests --haddock --no-haddock-deps

      - run: ./scripts/copy-docs.sh

      - run:
          name: Running unit tests
          command: stack test

      - save_cache:
          key: dot-stack-base
          paths:
            - ~/.stack

      - save_cache:
          key: dot-stack-{{ checksum "stack.yaml" }}-{{ checksum "datadog.cabal" }}
          paths:
            - ~/.stack

      - save_cache:
          key: stack-work-{{ checksum "stack.yaml" }}
          paths: ~/datadog/.stack-work

      - store_artifacts:
          path: /tmp/doc
