name: arbor-datadog
version: '0.0.0.1'
synopsis: Datadog client for Haskell.
description: Datadog client for Haskell. Supports both the HTTP API and StatsD.
category: Network
author: Arbor Networks
maintainer: mayhem@arbor.net
license: MIT
homepage: https://github.com/arbor/arbor-datadog
git: git://github.com/arbor/arbor-datadog.git

dependencies:
- generic-lens
- lens
- network
- resourcet
- time
- transformers

library:
  source-dirs: src
  other-extensions:
  - OverloadedStrings
  - GeneralizedNewtypeDeriving
  - TemplateHaskell
  - FunctionalDependencies
  - MultiParamTypeClasses
  - FlexibleInstances
  ghc-options: -Wall
  dependencies:
  - base >=4.7 && <5
  - aeson
  - auto-update
  - buffer-builder
  - bytestring
  - dlist
  - mtl
  - random
  - text
  - unordered-containers
  - vector

tests:
  datadog-api-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -Wall
    - -O3
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - Cabal
    - arbor-datadog
    - hspec
